puts "Print vs puts:"
puts "This is test using puts"
print "This is a test using print, "
puts "this is other test using puts again."
print "Practice 1, "
print "using print "
puts "and also using puts"
puts "so, here we go!"
